
project:
  name: start

spring:
  ai:
    openroute:
      api-key: ${SPRING_AI_OPENROUTE_API_KEY:}
    ollama:
      base-url: ${SPRING_AI_OLLAMA_BASE_URL}
      embedding:
        options:
          num-batch: 512
        model: nomic-embed-text
    rag:
      embed: nomic-embed-text
    zhipuai:
      api-key: ${ZHIPUAI_API_KEY}
    #      embedding-model: text-embedding-ada-002
    #    rag:
    #      embed: nomic-embed-text #nomic-embed-text、text-embedding-ada-002
#    vectorstore:
#      pgvector:
#        initialize-schema: true   # 首次启动自动建表
#        index-type: HNSW          # HNSW 近似最近邻索引
#        distance-type: COSINE_DISTANCE
#        dimensions: 1536          # 与所用 Embedding 模型维度一致
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    type: com.zaxxer.hikari.HikariDataSource
    # hikari连接池配置
    hikari:
      #连接池名
      pool-name: HikariCP
      #最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认10分钟
      idle-timeout: 600000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒
      connection-timeout: 30000
      # 连接测试query
      connection-test-query: SELECT 1
  data:
    redis:
      sdk:
        config:
          host: ${SPRING_DATA_REDIS_HOST}
          port: ${SPRING_DATA_REDIS_PORT}
          pool-size: 10
          min-idle-size: 5
          idle-timeout: 30000
          connect-timeout: 5000
          retry-attempts: 3
          retry-interval: 1000
          ping-interval: 60000
          keep-alive: true


feishu:
  appid: ${FEISHU_APPID}
  appsecret: ${FEISHU_APPSECRET}

    # YouTube Downloader API Configuration
youtube:
  downloader:
    api:
      url: ${YOUTUBE_DOWNLOADER_API_URL}
      key: YOUR_API_KEY_HERE



